import { ossPath } from '../../config/util'

export default {
  tab1: [
      {"id":"1","name":"康 康","gender":"女","age":"61","edu":"本科","pro":"心血管","level":"主任医师","years":"38","duty":"主检","exp":"14","page":"100"},
      {"id":"2","name":"徐冬娥","gender":"女","age":"52","edu":"硕士","pro":"内分泌","level":"主任医师","years":"30","duty":"主检","exp":"14","page":"100"},
      {"id":"3","name":"卢小军","gender":"女","age":"56","edu":"本科","pro":"内科","level":"主任医师","years":"34","duty":"内科","exp":"14","page":"101"},
      {"id":"4","name":"吴玉泉","gender":"男","age":"52","edu":"本科","pro":"内科","level":"主任医师","years":"30","duty":"内科","exp":"10","page":"101"},
      {"id":"5","name":"徐兰英","gender":"女","age":"64","edu":"本科","pro":"内科","level":"副主任医师","years":"42","duty":"内科","exp":"12","page":"102"},
      {"id":"6","name":"李 华","gender":"女","age":"34","edu":"本科","pro":"内科","level":"主治医师","years":"11","duty":"内科","exp":"10","page":"102"},
      {"id":"7","name":"鲁 任","gender":"男","age":"34","edu":"本科","pro":"内科","level":"主治医师","years":"9","duty":"内科","exp":"10","page":"103"},
      {"id":"8","name":"李良波","gender":"男","age":"31","edu":"本科","pro":"内科","level":"医师","years":"6","duty":"内科","exp":"10","page":"103"},
      {"id":"9","name":"蒋 燕","gender":"女","age":"31","edu":"本科","pro":"内科","level":"医师","years":"7","duty":"内科","exp":"9","page":"104"},
      {"id":"10","name":"史文婷","gender":"女","age":"29","edu":"本科","pro":"内科","level":"医师","years":"5","duty":"内科","exp":"8","page":"104"},
      {"id":"11","name":"郑 洁","gender":"女","age":"29","edu":"本科","pro":"内科","level":"医师","years":"5","duty":"内科","exp":"8","page":"105"},
      {"id":"12","name":"毛艺璇","gender":"女","age":"28","edu":"本科","pro":"内科","level":"医师","years":"5","duty":"内科","exp":"8","page":"105"},
      {"id":"13","name":"张翠莉","gender":"女","age":"27","edu":"本科","pro":"内科","level":"医师","years":"4","duty":"内科","exp":"8","page":"106"},
      {"id":"14","name":"楼 燕","gender":"女","age":"30","edu":"本科","pro":"内科","level":"医师","years":"5","duty":"内科","exp":"7","page":"106"},
      {"id":"15","name":"姜朝晖","gender":"男","age":"61","edu":"硕士","pro":"外科","level":"主任医师","years":"39","duty":"外科","exp":"14","page":"107"},
      {"id":"16","name":"林考兴","gender":"男","age":"57","edu":"硕士","pro":"外科","level":"主任医师","years":"35","duty":"外科","exp":"14","page":"107"},
      {"id":"17","name":"陈 兵","gender":"男","age":"52","edu":"本科","pro":"外科","level":"副主任医师","years":"30","duty":"外科","exp":"11","page":"108"},
      {"id":"18","name":"方晓明","gender":"男","age":"51","edu":"博士","pro":"外科","level":"副主任医师","years":"29","duty":"外科","exp":"12","page":"108"},
      {"id":"19","name":"姚 宁","gender":"男","age":"42","edu":"硕士","pro":"外科","level":"主治医师","years":"20","duty":"外科","exp":"9","page":"109"},
      {"id":"20","name":"方旭东","gender":"男","age":"43","edu":"硕士","pro":"外科","level":"主治医师","years":"21","duty":"外科","exp":"9","page":"109"},
      {"id":"21","name":"陈琪枫","gender":"男","age":"39","edu":"博士","pro":"外科","level":"主治医师","years":"17","duty":"外科","exp":"9","page":"110"},
      {"id":"22","name":"龚谋春","gender":"男","age":"38","edu":"博士","pro":"外科","level":"主治医师","years":"16","duty":"外科","exp":"9","page":"110"},
      {"id":"23","name":"李 峰","gender":"男","age":"37","edu":"本科","pro":"泌尿外科","level":"主治医师","years":"13","duty":"外科","exp":"9","page":"111"},
      {"id":"24","name":"符 二","gender":"女","age":"32","edu":"本科","pro":"泌尿外科","level":"主治医师","years":"9","duty":"外科","exp":"10","page":"111"},
      {"id":"25","name":"李彩云","gender":"女","age":"47","edu":"硕士","pro":"妇产科","level":"副主任医师","years":"27","duty":"妇科","exp":"10","page":"112"},
      {"id":"26","name":"罗蓉蓉","gender":"女","age":"60","edu":"本科","pro":"妇产科","level":"副主任医师","years":"38","duty":"妇科","exp":"14","page":"112"},
      {"id":"27","name":"张峥程","gender":"女","age":"48","edu":"硕士","pro":"妇产科","level":"副主任医师","years":"26","duty":"妇科","exp":"12","page":"113"},
      {"id":"28","name":"毛静月","gender":"女","age":"40","edu":"硕士","pro":"妇科","level":"主治医师","years":"18","duty":"妇科","exp":"10","page":"113"},
      {"id":"29","name":"侍立峰","gender":"男","age":"38","edu":"硕士","pro":"妇产科","level":"主治医师","years":"16","duty":"妇科","exp":"9","page":"114"},
      {"id":"30","name":"苌伟静","gender":"女","age":"28","edu":"本科","pro":"妇产科","level":"医 师","years":"6","duty":"妇科","exp":"4","page":"114"},
      {"id":"31","name":"宋 斗","gender":"男","age":"45","edu":"本科","pro":"眼科","level":"副主任医师","years":"23","duty":"眼科","exp":"14","page":"115"},
      {"id":"32","name":"陈 杰","gender":"男","age":"47","edu":"硕士","pro":"眼科","level":"主治医师","years":"25","duty":"眼科","exp":"13","page":"115"},
      {"id":"33","name":"尤 媛","gender":"女","age":"35","edu":"本科","pro":"眼科","level":"主治医师","years":"13","duty":"眼科","exp":"9","page":"116"},
      {"id":"34","name":"袁 翊","gender":"男","age":"32","edu":"本科","pro":"眼科","level":"主治医师","years":"8","duty":"眼科","exp":"6","page":"116"},
      {"id":"35","name":"孙佳黎","gender":"女","age":"32","edu":"本科","pro":"眼科","level":"主治医师","years":"10","duty":"眼科","exp":"8","page":"117"},
      {"id":"36","name":"葛 薇","gender":"女","age":"29","edu":"硕士","pro":"眼科","level":"医师","years":"3","duty":"眼科","exp":"3","page":"117"},
      {"id":"37","name":"马超武","gender":"男","age":"53","edu":"本科","pro":"耳鼻喉","level":"主任医师","years":"31","duty":"耳鼻喉科","exp":"14","page":"118"},
      {"id":"38","name":"徐建中","gender":"男","age":"43","edu":"硕士","pro":"耳鼻喉","level":"主治医师","years":"21","duty":"耳鼻喉科","exp":"13","page":"118"},
      {"id":"39","name":"高陈恺","gender":"男","age":"34","edu":"硕士","pro":"耳鼻喉","level":"医师","years":"12","duty":"耳鼻喉科","exp":"11","page":"119"},
      {"id":"40","name":"周 宇","gender":"女","age":"35","edu":"本科","pro":"耳鼻喉","level":"医师","years":"10","duty":"耳鼻喉科","exp":"5","page":"119"},
      {"id":"41","name":"任艳云","gender":"女","age":"48","edu":"本科","pro":"口腔科","level":"副主任医师","years":"26","duty":"口腔科","exp":"14","page":"120"},
      {"id":"42","name":"王利明","gender":"男","age":"44","edu":"硕士","pro":"口腔科","level":"主任医师","years":"22","duty":"口腔科","exp":"13","page":"120"},
      {"id":"43","name":"李 斌","gender":"男","age":"42","edu":"本科","pro":"口腔科","level":"主任医师","years":"20","duty":"口腔科","exp":"12","page":"121"},
      {"id":"44","name":"张吉敏","gender":"男","age":"31","edu":"本科","pro":"口腔科","level":"主任医师","years":"7","duty":"口腔科","exp":"5","page":"121"},
      {"id":"45","name":"张 宏","gender":"男","age":"43","edu":"本科","pro":"心 电","level":"副主任医师","years":"21","duty":"心电图","exp":"14","page":"122"},
      {"id":"46","name":"张木兰","gender":"女","age":"45","edu":"本科","pro":"心 电","level":"主治医师","years":"25","duty":"心电图","exp":"14","page":"123"},
      {"id":"47","name":"余秀华","gender":"女","age":"50","edu":"本科","pro":"超 声","level":"副主任医师","years":"30","duty":"B 超","exp":"14","page":"124"},
      {"id":"48","name":"施 红","gender":"女","age":"64","edu":"本科","pro":"超 声","level":"主任医师","years":"32","duty":"B 超","exp":"14","page":"124"},
      {"id":"49","name":"钱 斌","gender":"女","age":"42","edu":"本科","pro":"超 声","level":"主治医师","years":"20","duty":"B 超","exp":"13","page":"125"},
      {"id":"50","name":"卫张蕊","gender":"女","age":"36","edu":"博士","pro":"超 声","level":"主治医师","years":"14","duty":"B 超","exp":"12","page":"125"},
      {"id":"51","name":"孔梓祥","gender":"男","age":"34","edu":"本科","pro":"超 声","level":"主治医师","years":"12","duty":"B 超","exp":"8","page":"126"},
      {"id":"52","name":"冯 婷","gender":"女","age":"32","edu":"硕士","pro":"超 声","level":"医师","years":"9","duty":"B 超","exp":"8","page":"126"},
      {"id":"53","name":"姚烨菲","gender":"女","age":"29","edu":"本科","pro":"超 声","level":"医师","years":"7","duty":"B 超","exp":"6","page":"127"},
      {"id":"54","name":"张 斌","gender":"男","age":"32","edu":"本科","pro":"超 声","level":"医师","years":"4","duty":"B 超","exp":"4","page":"127"},
      {"id":"55","name":"陈海萍","gender":"女","age":"27","edu":"本科","pro":"超 声","level":"医师","years":"4","duty":"B 超","exp":"4","page":"128"},
      {"id":"56","name":"朱 进","gender":"男","age":"29","edu":"本科","pro":"超 声","level":"医师","years":"4","duty":"B 超","exp":"4","page":"128"},
      {"id":"57","name":"苗柴晶","gender":"女","age":"28","edu":"本科","pro":"超 声","level":"医师","years":"4","duty":"B 超","exp":"4","page":"129"},
      {"id":"58","name":"戴 飞","gender":"女","age":"28","edu":"本科","pro":"超 声","level":"医师","years":"4","duty":"B 超","exp":"4","page":"129"},
      {"id":"59","name":"楼 阳","gender":"女","age":"28","edu":"本科","pro":"超 声","level":"医师","years":"3","duty":"B 超","exp":"3","page":"130"},
      {"id":"60","name":"陈兴灿","gender":"男","age":"53","edu":"博士","pro":"放 射","level":"主任医师","years":"20","duty":"放 射","exp":"14","page":"130"},
      {"id":"61","name":"潘建虎","gender":"男","age":"53","edu":"本科","pro":"放 射","level":"副主任医师","years":"23","duty":"放 射","exp":"14","page":"131"},
      {"id":"62","name":"刘 淼","gender":"男","age":"42","edu":"本科","pro":"放 射","level":"主治医师","years":"20","duty":"放 射","exp":"14","page":"131"},
      {"id":"63","name":"何 东","gender":"男","age":"37","edu":"硕士","pro":"放 射","level":"主治医师","years":"15","duty":"放 射","exp":"12","page":"132"},
      {"id":"64","name":"沈小东","gender":"男","age":"41","edu":"本科","pro":"放 射","level":"主治医师","years":"20","duty":"放 射","exp":"10","page":"132"},
      {"id":"65","name":"韩 宁","gender":"男","age":"27","edu":"本科","pro":"放 射","level":"医师","years":"6","duty":"放 射","exp":"5","page":"133"},
      {"id":"66","name":"吕 彪","gender":"男","age":"26","edu":"本科","pro":"放 射","level":"医师","years":"5","duty":"放 射","exp":"5","page":"133"},
      {"id":"67","name":"辛科道","gender":"男","age":"28","edu":"本科","pro":"放 射","level":"医师","years":"6","duty":"放 射","exp":"5","page":"134"},
      {"id":"68","name":"陈泯涵","gender":"男","age":"26","edu":"本科","pro":"放 射","level":"医师","years":"4","duty":"放 射","exp":"4","page":"134"},
      {"id":"69","name":"孙长贵","gender":"男","age":"53","edu":"本科","pro":"检 验","level":"主任技师","years":"31","duty":"检 验","exp":"14","page":"135"},
      {"id":"70","name":"成 军","gender":"男","age":"48","edu":"硕士","pro":"检 验","level":"副主任医师","years":"26","duty":"检 验","exp":"14","page":"135"},
      {"id":"71","name":"沈雄文","gender":"男","age":"45","edu":"硕士","pro":"检 验","level":"副主任技师","years":"23","duty":"检 验","exp":"13","page":"136"},
      {"id":"72","name":"徐 胜","gender":"男","age":"33","edu":"硕士","pro":"检 验","level":"主管技师","years":"11","duty":"检 验","exp":"11","page":"136"},
      {"id":"73","name":"周华君","gender":"男","age":"32","edu":"本科","pro":"检 验","level":"主管技师","years":"10","duty":"检 验","exp":"9","page":"137"},
      {"id":"74","name":"戴玉柱","gender":"男","age":"35","edu":"本科","pro":"检 验","level":"主管技师","years":"12","duty":"检 验","exp":"10","page":"137"},
      {"id":"75","name":"胡云华","gender":"男","age":"32","edu":"本科","pro":"检 验","level":"技师","years":"10","duty":"检 验","exp":"10","page":"138"},
      {"id":"76","name":"裘敏丽","gender":"女","age":"29","edu":"本科","pro":"检 验","level":"技师","years":"6","duty":"检 验","exp":"6","page":"138"},
      {"id":"77","name":"车飞虎","gender":"男","age":"29","edu":"本科","pro":"检 验","level":"技师","years":"5","duty":"检 验","exp":"5","page":"139"},
      {"id":"78","name":"谭焕腾","gender":"男","age":"29","edu":"本科","pro":"检 验","level":"技师","years":"5","duty":"检 验","exp":"5","page":"139"},
      {"id":"79","name":"张 敏","gender":"女","age":"28","edu":"本科","pro":"检 验","level":"技师","years":"6","duty":"检 验","exp":"6","page":"140"},
      {"id":"80","name":"林 迪","gender":"女","age":"28","edu":"本科","pro":"检 验","level":"技师","years":"6","duty":"检 验","exp":"6","page":"140"},
      {"id":"81","name":"占小飞","gender":"男","age":"27","edu":"本科","pro":"检 验","level":"技师","years":"3","duty":"检 验","exp":"3","page":"141"},
      {"id":"82","name":"王 磊","gender":"男","age":"27","edu":"本科","pro":"检 验","level":"技师","years":"5","duty":"检 验","exp":"5","page":"141"},
      {"id":"83","name":"陈 坚","gender":"男","age":"29","edu":"本科","pro":"检 验","level":"技师","years":"6","duty":"检 验","exp":"6","page":"142"},
      {"id":"84","name":"金晓娟","gender":"女","age":"35","edu":"本科","pro":"检 验","level":"技师","years":"16","duty":"检 验","exp":"14","page":"142"},
      {"id":"85","name":"刘 肖","gender":"女","age":"32","edu":"本科","pro":"检 验","level":"技师","years":"11","duty":"检 验","exp":"9","page":"143"},
      {"id":"86","name":"徐 莉","gender":"女","age":"28","edu":"本科","pro":"检 验","level":"技师","years":"3","duty":"检 验","exp":"3","page":"143"},
      {"id":"87","name":"陈 琼","gender":"女","age":"32","edu":"本科","pro":"检 验","level":"技师","years":"9","duty":"检 验","exp":"9","page":"144"},
      {"id":"88","name":"汪 艳","gender":"女","age":"28","edu":"本科","pro":"检 验","level":"技师","years":"6","duty":"检 验","exp":"6","page":"144"},
      {"id":"89","name":"金 晶","gender":"女","age":"35","edu":"本科","pro":"护 理","level":"护 师","years":"15","duty":"测血压","exp":"14","page":"145"},
      {"id":"90","name":"李 瑶","gender":"女","age":"31","edu":"本科","pro":"护 理","level":"护 师","years":"12","duty":"测血压","exp":"10","page":"145"},
      {"id":"91","name":"孙 珍","gender":"女","age":"29","edu":"本科","pro":"护 理","level":"护 师","years":"11","duty":"身高体重","exp":"11","page":"146"},
      {"id":"92","name":"李园园","gender":"女","age":"31","edu":"本科","pro":"护 理","level":"护 师","years":"9","duty":"身高体重","exp":"9","page":"146"},
      {"id":"93","name":"王 芳","gender":"女","age":"27","edu":"本科","pro":"护 理","level":"护 师","years":"7","duty":"导 检","exp":"7","page":"147"},
      {"id":"94","name":"胡丹蓉","gender":"女","age":"27","edu":"本科","pro":"护 理","level":"护 师","years":"8","duty":"导 检","exp":"8","page":"147"},
      {"id":"95","name":"林龙芳","gender":"女","age":"42","edu":"本科","pro":"护 理","level":"护 师","years":"20","duty":"导 检","exp":"14","page":"148"},
      {"id":"96","name":"蔡柯熹","gender":"女","age":"28","edu":"本科","pro":"护 理","level":"护 师","years":"5","duty":"导 检","exp":"5","page":"148"},
      {"id":"97","name":"赵 静","gender":"女","age":"27","edu":"本科","pro":"护 理","level":"护 师","years":"4","duty":"导 检","exp":"4","page":"149"},
      {"id":"98","name":"马雪梅","gender":"女","age":"25","edu":"本科","pro":"护 理","level":"护 师","years":"5","duty":"导 检","exp":"5","page":"149"},
      {"id":"99","name":"付玉洁","gender":"女","age":"25","edu":"本科","pro":"护 理","level":"护 士","years":"3","duty":"导 检","exp":"3","page":"150"},
      {"id":"100","name":"罗小娟","gender":"女","age":"26","edu":"本科","pro":"护 理","level":"护 士","years":"4","duty":"导 检","exp":"4","page":"150"},
      {"id":"101","name":"鲁 琼","gender":"女","age":"33","edu":"本科","pro":"护 理","level":"护 师","years":"13","duty":"导 检","exp":"13","page":"151"},
      {"id":"102","name":"杨泉萍","gender":"女","age":"28","edu":"本科","pro":"护 理","level":"护 士","years":"8","duty":"导 检","exp":"8","page":"151"},
      {"id":"103","name":"方 燕","gender":"女","age":"24","edu":"本科","pro":"护 理","level":"护 士","years":"3","duty":"导 检","exp":"3","page":"152"},
      {"id":"104","name":"杨海亚","gender":"女","age":"25","edu":"本科","pro":"护 理","level":"护 士","years":"3","duty":"导 检","exp":"3","page":"152"},
      {"id":"105","name":"丁 洁","gender":"女","age":"24","edu":"本科","pro":"护 理","level":"护 士","years":"3","duty":"导 检","exp":"3","page":"153"},
      {"id":"106","name":"贲美娟","gender":"女","age":"23","edu":"本科","pro":"护 理","level":"护 士","years":"2","duty":"导 检","exp":"2","page":"153"},
      {"id":"107","name":"靳利敏","gender":"女","age":"24","edu":"本科","pro":"护 理","level":"护 士","years":"2","duty":"导 检","exp":"2","page":"154"},
      {"id":"108","name":"孙 露","gender":"女","age":"31","edu":"本科","pro":"护 理","level":"护 师","years":"10","duty":"导 检","exp":"10","page":"154"},
      {"id":"109","name":"沈 琳","gender":"女","age":"27","edu":"本科","pro":"护 理","level":"护 士","years":"6","duty":"导 检","exp":"6","page":"155"},
      {"id":"110","name":"李潇锋","gender":"男","age":"23","edu":"本科","pro":"护 理","level":"护 士","years":"2","duty":"导 检","exp":"2","page":"155"},
      {"id":"111","name":"朱 珺","gender":"女","age":"24","edu":"本科","pro":"护 理","level":"护 士","years":"2","duty":"导 检","exp":"2","page":"156"},
      {"id":"112","name":"白菁雯","gender":"女","age":"22","edu":"本科","pro":"护 理","level":"护 士","years":"2","duty":"导 检","exp":"2","page":"156"}
  ],

  tab2: [
    ossPath + "zhengjian01.png",
    ossPath + "zhengjian02.png",
    ossPath + "zhengjian03.png",
    ossPath + "zhengjian04.png",
    ossPath + "zhengjian05.png",
    ossPath + "zhengjian06.png",
    ossPath + "zhengjian07.png",
    ossPath + "zhengjian08.png",
    ossPath + "zhengjian09.png",
    ossPath + "zhengjian10.png",
    ossPath + "zhengjian11.png",
    ossPath + "zhengjian12.png",
    ossPath + "zhengjian13.png",
    ossPath + "zhengjian14.png",
    ossPath + "zhengjian15.png",
    ossPath + "zhengjian16.png",
    ossPath + "zhengjian17.png",
    ossPath + "zhengjian18.png",
    ossPath + "zhengjian19.png",
    ossPath + "zhengjian20.png",
    ossPath + "zhengjian21.png",
    ossPath + "zhengjian22.png",
    ossPath + "zhengjian23.png",
    ossPath + "zhengjian24.png",
    ossPath + "zhengjian25.png",
    ossPath + "zhengjian26.png",
    ossPath + "zhengjian27.png",
    ossPath + "zhengjian28.png",
    ossPath + "zhengjian29.png",
    ossPath + "zhengjian30.png",
    ossPath + "zhengjian31.png",
    ossPath + "zhengjian32.png",
    ossPath + "zhengjian33.png",
    ossPath + "zhengjian34.png",
    ossPath + "zhengjian35.png",
    ossPath + "zhengjian36.png",
    ossPath + "zhengjian37.png",
    ossPath + "zhengjian38.png",
    ossPath + "zhengjian39.png",
    ossPath + "zhengjian40.png",
    ossPath + "zhengjian41.png",
    ossPath + "zhengjian42.png",
    ossPath + "zhengjian43.png",
    ossPath + "zhengjian44.png",
    ossPath + "zhengjian45.png",
    ossPath + "zhengjian46.png",
    ossPath + "zhengjian47.png",
    ossPath + "zhengjian48.png",
    ossPath + "zhengjian49.png",
    ossPath + "zhengjian50.png",
    ossPath + "zhengjian51.png",
    ossPath + "zhengjian52.png",
    ossPath + "zhengjian53.png",
    ossPath + "zhengjian54.png",
    ossPath + "zhengjian55.png",
    ossPath + "zhengjian56.png",
    ossPath + "zhengjian57.png",
    ossPath + "zhengjian58.png",
    ossPath + "zhengjian59.png",
    ossPath + "zhengjian60.png",
    ossPath + "zhengjian61.png",
    ossPath + "zhengjian62.png",
    ossPath + "zhengjian63.png",
    ossPath + "zhengjian64.png",
    ossPath + "zhengjian65.png",
    ossPath + "zhengjian66.png",
    ossPath + "zhengjian67.png",
    ossPath + "zhengjian68.png",
    ossPath + "zhengjian69.png",
    ossPath + "zhengjian70.png",
    ossPath + "zhengjian71.png",
    ossPath + "zhengjian72.png",
    ossPath + "zhengjian73.png",
    ossPath + "zhengjian74.png",
    ossPath + "zhengjian75.png",
    ossPath + "zhengjian76.png",
    ossPath + "zhengjian77.png",
    ossPath + "zhengjian78.png",
    ossPath + "zhengjian79.png",
    ossPath + "zhengjian80.png",
    ossPath + "zhengjian81.png",
    ossPath + "zhengjian82.png",
    ossPath + "zhengjian83.png",
    ossPath + "zhengjian84.png",
    ossPath + "zhengjian85.png",
    ossPath + "zhengjian86.png",
    ossPath + "zhengjian87.png",
    ossPath + "zhengjian88.png",
    ossPath + "zhengjian89.png",
    ossPath + "zhengjian90.png",
    ossPath + "zhengjian91.png",
    ossPath + "zhengjian92.png",
    ossPath + "zhengjian93.png",
    ossPath + "zhengjian94.png",
    ossPath + "zhengjian95.png",
    ossPath + "zhengjian96.png",
    ossPath + "zhengjian97.png",
    ossPath + "zhengjian98.png",
    ossPath + "zhengjian99.png",
    ossPath + "zhengjian100.png"
    ,ossPath + "zhengjian101.png",
    ossPath + "zhengjian102.png",
    ossPath + "zhengjian103.png",
    ossPath + "zhengjian104.png",
    ossPath + "zhengjian105.png",
    ossPath + "zhengjian106.png",
    ossPath + "zhengjian107.png",
    ossPath + "zhengjian108.png",
    ossPath + "zhengjian109.png",
    ossPath + "zhengjian110.png",
    ossPath + "zhengjian111.png",
    ossPath + "zhengjian112.png",
    ossPath + "zhengjian113.png",
    ossPath + "zhengjian114.png"
  ],

  tab3: [
    {"name":"X光机","standard":"PLD-6000","num":"1","status":"在用","from":"韩国新黄浦公司","date":"2012年5月"},
    {"name":"宝石能谱CT","standard":"Discowery CT750","num":"1","status":"在用","from":"美国GE公司","date":"2013年5月"},
    {"name":"全身PET/CT","standard":"DISCOVERY-16ST","num":"1","status":"在用","from":"美国GE公司","date":"2014年10月"},
    {"name":"彩色多普勒超声诊断仪","standard":"DC-8","num":"2","status":"在用","from":"深圳迈瑞电子有限公司","date":"2014年3月"},
    {"name":"彩色多普勒超声诊断仪","standard":"M7","num":"1","status":"在用","from":"深圳迈瑞电子有限公司","date":"2014年3月"},
    {"name":"彩色多普勒超声诊断仪","standard":"DC-7","num":"2","status":"在用","from":"深圳迈瑞电子有限公司","date":"2011年11月"},
    {"name":"彩色多普勒超声诊断仪","standard":"L5","num":"2","status":"在用","from":"美国GE公司","date":"2011年1月"},
    {"name":"彩色多普勒超声诊断仪","standard":"P5","num":"2","status":"在用","from":"美国GE公司","date":"2012年3月"},
    {"name":"心电图机","standard":"CN100","num":"4","status":"在用","from":"上海华泰医疗器械有限公司","date":"2012年1月"},
    {"name":"动态心电图","standard":"ELITE-12A","num":"3","status":"在用","from":"北京福田","date":"2010年9月"},
    {"name":"动态血压","standard":"MOBILO GRAPH","num":"3","status":"在用","from":"欧姆龙（大连）有限公司","date":"2010年9月"},
    {"name":"身高体重测量仪","standard":"SK-CK","num":"1","status":"在用","from":"深圳市双佳电子设备有限公司","date":"2013年3月"},
    {"name":"电子血压计","standard":"HBP-9020","num":"2","status":"在用","from":"欧姆龙（大连）有限公司","date":"2013年3月"},
    {"name":"台式血压计","standard":"XJ11D","num":"3","status":"在用","from":"上海医疗器械股份有限公司（玉兔）","date":"2013年5月"},
    {"name":"眼底照相机","standard":"NW200","num":"1","status":"在用","from":"日本拓普康","date":"2010年6月"},
    {"name":"眼底镜","standard":"YZ6F","num":"1","status":"在用","from":"上海医疗器械工业集团公司","date":"2011年5月"},
    {"name":"裂隙灯","standard":"SL-20","num":"1","status":"在用","from":"日本尼德克公司","date":"2012年1月"},
    {"name":"眼压仪","standard":"Reichert7","num":"1","status":"在用","from":"美国莱卡","date":"2015年6月"},
    {"name":"生化分析仪","standard":"ADVIA2400","num":"1","status":"在用","from":"西门子医学诊断有限公司","date":"2012年3月"},
    {"name":"免疫分析仪","standard":"ROCHE e411","num":"1","status":"在用","from":"德国罗氏","date":"2012年3月"},
    {"name":"全自动血液细胞分析仪","standard":"SYSMEX XE-2100","num":"1","status":"在用","from":"希森美康","date":"2012年3月"},
    {"name":"电解质分析仪","standard":"EasyLyte PLUS","num":"1","status":"在用","from":"MEDICA CORPORATION","date":"2014年10月"},
    {"name":"自动粪便分析仪","standard":"ZH-300","num":"1","status":"在用","from":"苏州迈迪达医疗器械科技有限公司","date":"2014年5月"},
    {"name":"全自动尿液分析仪","standard":"LX5000","num":"1","status":"在用","from":"杭州龙鑫科技有限公司","date":"2010年3月"},
    {"name":"妇科检查床","standard":"WX-C1280J1","num":"2","status":"在用","from":"台湾三丰","date":"2014年1月"},
    {"name":"牙科综合治疗机","standard":"S2308","num":"2","status":"在用","from":"西安西诺","date":"2006年3月"},
    {"name":"眼底照相机","standard":"TRC-NW200","num":"1","status":"在用","from":"日本拓普康","date":"2007年6月"},
    {"name":"五官科综合治疗台","standard":"XD-2400CC","num":"1","status":"在用","from":"安徽宣城先达医疗器械有限公司","date":"2014年1月"},
    {"name":"乙状结肠镜","standard":"STL-001","num":"3","status":"在用","from":"广州佛山市科源设备有限公司","date":"2011年9月"},
    {"name":"电子胃镜","standard":"GIF-XQ260","num":"2","status":"在用","from":"日本欧林巴斯株式会社","date":"2012年12月"},
    {"name":"肺功能测定仪","standard":"minispir","num":"2","status":"在用","from":"意大利MIR","date":"2013年9月"},
    {"name":"经颅多普勒超声诊断仪","standard":"SONARA TEK ","num":"2","status":"在用","from":"美国VIASYS","date":"2012年12月"},
    {"name":"动脉硬化诊断仪","standard":"科林","num":"2","status":"在用","from":"欧姆龙（大连）有限公司","date":"2012年12月"},
    {"name":"超声骨密度测量仪","standard":"SONOST3000","num":"2","status":"在用","from":"韩国BIONET","date":"2012年5月"},
    {"name":"HP测试仪（C14）","standard":"无","num":"1","status":"在用","from":"深圳海德威","date":"2013年5月"},
    {"name":"HP测试仪（C13）","standard":"无","num":"2","status":"在用","from":"深圳海德威","date":"2013年9月"},
    {"name":"电动诊疗床","standard":"190＊63＊65","num":"188","status":"在用","from":"中山市仲景医疗器械有限公司","date":"2011年11月"}
  ]
}
